### ISSUE TITLE
Get error saying "Unable to comment on PR" on every build

### ISSUE THREAD

**Issue by ejsmith** [daun/playwright-report-summary#107]
Any idea why it's not working or if I can disable it?

![image](https://github.com/daun/playwright-report-summary/assets/282584/f2076681-576b-4b8c-a2ac-feaf428bbcc5)

**Comment by daun** [comment]
Going from the error message, it looks like the action doesn't have write permissions to the repo. Without seeing the workflow file and/or repo you're using it in, it's hard to be any more specific. You might try [enabling debug logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) for your GitHub actions, see if that turns up any clues.

**Comment by ssalka** [comment]
In case someone else comes along this, I had the same issue in and just had to update my repo settings (Actions > General >Workflow permissions) to give write permissions to the `GITHUB_TOKEN` used for workflows
