### ISSUE TITLE
[Feature request] Add the ability to add the summary on the workflow run without the PR comment

### ISSUE THREAD

**Issue by larmitage-bjss** [daun/playwright-report-summary#141]
Currently you can only run this action on workflows triggered by "pull_request", "pull_request_target", and "push" otherwise you get an error:
> Unsupported event type: workflow_dispatch. Only "pull_request", "pull_request_target", and "push" triggered workflows are currently supported.

I would like to be able to run this action on my main release build and test workflow which is triggered by release creation in order to get the playwright summary on the workflow

Please would you be able to add functionality to enable being able to add the summary to the workflow without needing the PR to add a comment on?

The way this could work is with an input option to skip the PR comment, or if the trigger is not one of the types above it does not error and will continue without the comment but adding the summary if that option is turned on

**Comment by daun** [comment]
Sounds like a reasonable use case to support. The reason it's currently not supported is that we're relying on an actual PR to extract the required data from the action run's payload. I'll do some research to see how much work this would be.

**Comment by larmitage-bjss** [comment]
Thanks for the speedy response, that would be great, thank you!

**Comment by daun** [comment]
Wasn't that much work :) I've released [v3.1.0](https://github.com/daun/playwright-report-summary/releases/tag/v3.1.0) with support for manual workflow dispatch. Let me know how it goes!

**Comment by larmitage-bjss** [comment]
Amazing! Thank you so much, quickest response and solution ever! Would it be possible to add it for `release` triggers as well? No rush at all! Thanks

**Comment by daun** [comment]
I've released [v3.2.0](https://github.com/daun/playwright-report-summary/releases/tag/v3.2.0) which will merely print a warning instead of aborting on unknown events. No guarantees 🧃

**Comment by larmitage-bjss** [comment]
FYI this is working perfectly on a release creation workflow, thank you!

**Comment by azad-resolver** [comment]
@larmitage-bjss I'm curious, how do you add the summary to the workflow?
What I've been looking for is to add these details from the summary to the description of the PR workflow:
<img width="844" alt="image" src="https://github.com/user-attachments/assets/81568e1b-5e6b-4a4d-a2e6-c4394b1ea53b">
If there's really a way to get them from this GH Action, that would be a huge help!

**Comment by daun** [comment]
@sivaramkumar2908 I'm not sure I understand the exact use case. How would the action find out there's a PR if the workflow was dispatched manually? If it requires an API call as in your example, I'd prefer not to handle this in the action itself. Feels like a bit of an edge case that could be handled by combining this with other actions. You'll find the report summary as an [output variable](https://github.com/daun/playwright-report-summary?tab=readme-ov-file#summary) which you could use in other actions run after this one.

**Comment by daun** [comment]
@sivaramkumar2908 I'm currently looking into slimming down the action, and only make it generate the raw markdown summary. Users would then be free to use other actions to find the PR and comment on it in whatever fashion useful to them. Separation of concerns :) So I probably won't be tackling your requested feature for now — however I found this action that might be useful to you: [jwalton/gh-find-current-pr](https://github.com/jwalton/gh-find-current-pr)
