### ISSUE TITLE
[Feature Request] Add an additional details option

### ISSUE THREAD

**Issue by fungairino** [daun/playwright-report-summary#199]
It would be nice to include additional information into the report summary that's not directly part of the report. 

Ex. instructions for the PR submitter on how to investigate failures, links to relevant playwright docs or what to do about flaky tests.

**Comment by daun** [comment]
Great suggestions. It's not something I currently need, so I'm a bit hesitant about adding it myself. I'll happily accept a PR and take it from there, however, if you have specific ideas!

**Comment by fungairino** [comment]
Sure thing, here you go:
https://github.com/daun/playwright-report-summary/pull/200/files
