### ISSUE TITLE
Summary is not added when pushing changes

### ISSUE THREAD

**Issue by jkalberer** [daun/playwright-report-summary#207]
I have a PR in draft mode that I've been pushing changes to.

I'd expect that it would run this action and add a comment after a successful CI run but it's failing since the `pr` variable isn't being set here - https://github.com/daun/playwright-report-summary/blob/main/src/index.ts#L73-L77

I'm not sure if just adding `pr = issueNumber` would fix this or not but ideally I should have control over when this action runs and updates the comment -- not the action itself (does that make sense?).

I'm going to try to fork this to see if I can get things working. If it does, I'll open a PR.

**Comment by daun** [comment]
I personally would have expected the action to not run at all on draft PRs. If you find a way to do this, a PR sounds great!

**Comment by daun** [comment]
@jkalberer I think I misunderstood your question.

When you open a PR, the action first adds a comment containing the test result. Pushing additional commits to the PR branch will update the existing comment to show the new test results. It won't create new comments. If you're not seeing that, it's probably a configuration issue. From a bit of research, the PR being a draft shouldn't make a difference here.

I'll close this for now, but feel free to get back if you're still seeing the issue.
