### ISSUE TITLE
Unsupported event type deployment_status

### ISSUE THREAD

**Issue by baryosef-loops** [daun/playwright-report-summary#208]
Hey,

When used in a workflow that has the trigger of type
```
on: 
  deployment_status
```

The action can't recognize the PR, this is the output I get

```
Unsupported event type: deployment_status
No PR associated with this action run. Not posting a check or comment.
```

Is there a workaround or possible to fix?

**Comment by daun** [comment]
I'm not familiar with that workflow trigger, but how would the action know which pull request to comment on? That's usually the challenge when using triggers other than `pull_request`. Feel free to share your current workflow setup.

**Comment by baryosef-loops** [comment]
Agree, this event is not only for PRs, it also run on branch level. 

In general it is possible to test if SHA belong to some PR or can be used in github API as best effort, and in the worst case, the API call just fail.

For example, this is the CURL that I am using to set `check status` in the workflow, maybe this may be helpful to figure out how to construct similar call for sending a `comment`? 

```
curl -X POST \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}" \
            -H "Authorization: ***** " \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{ "sha": "${{ github.sha }}", "state": "***", "target_url": "***", "description": "***", "context": "***" }'
```


I can share more parts of the workflow, need to sanitize it a bit first :)

**Comment by daun** [comment]
How would such an API look like? I could imagine allowing users to pass in the pull request number themselves. That would remove the burden from the action to also figure out all the context.

**Comment by daun** [comment]
@baryosef-loops I'm closing this for now as I can't quite see how this action would respond to a deployment status event. Please share some more detail on the use case and/or a link to your actual workflow file to fill in the blanks :)

**Comment by baryosef-loops** [comment]
@daun thank you, I will try to figure the requirements to share in the future

**Comment by lohani-mohit** [comment]
Hey @baryosef-loops I also run into the same thing, do you found an alternative?

**Comment by baryosef-loops** [comment]
@lohani-mohit Hi, unfortunately I didn't find any alternative, hence using this action is not an option for my workflows currently

**Comment by lohani-mohit** [comment]
Thanks, @baryosef-loops,
I created a script that parses the JSON report and comments on the PR with the test status.

What I did was retrieve the pull request from the deployment SHA using `github.event.deployment.sha` and the repository name through `github.repository` 
Then, I obtained the PR number using the deployment SHA via this endpoint: `https://api.github.com/repos/${repo}/commits/${deploymentSha}/pulls`

Finally, I posted a comment on the PR using the endpoint: `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`

Let me know if you need help on this one.

@daun , you can use a similar logic in your repo as well. It's just about finding the PR number.
May be I will fork and try creating a Pr later on this one. 

Thanks, happy to help 🙏

**Comment by daun** [comment]
@lohani-mohit Sounds great, if you do find the time to create a PR, I'll happily take a look :) Long-term, I've been thinking about removing support for the actual commenting in favor of people using other actions specifically made for that purpose, but that's not going to happen too soon anyway so a PR is certainly welcome.
