### ISSUE TITLE
[Feature] Add more details

### ISSUE THREAD

**Issue by huehnerlady** [daun/playwright-report-summary#209]
Hi, 

would be cool if you could have another section like the flaky tests section, which then shows also the tests that passed. That is helpful when you think the number is quite low/high. Maybe you run something twice or you skip some by accident.

What do you think?

**Comment by daun** [comment]
The main goal of the action is showing a high-level overview of test results as a quick sanity check — or as a jumping off point in case of failures by linking to the generated html report. Your idea goes more into detailed reporting territory, which is a valid use case but maybe too much to ask of this particular action? Let me think on it :)

**Comment by huehnerlady** [comment]
we are using a different tool now, so for us it is not needed anymore
