### ISSUE TITLE
[Feature] "Sticky" comment

### ISSUE THREAD

**Issue by olafurns7** [daun/playwright-report-summary#215]
Hi,

Thanks for this great action!

## Idea
It would be a great additional option to somehow make the comment "sticky", or basically hijack some of the features that this action does: [https://github.com/marocchino/sticky-pull-request-comment](https://github.com/marocchino/sticky-pull-request-comment)

## Why
During my implementation of our workflows, and incorporating your action, I did **a lot** of commits, and the initial comment created by this action can get lost in a sea of commits. I know this, might be a fringe case, but it still would be a good option to be able to keep the test result comment always visible/sticky

**Comment by daun** [comment]
Hi! What's your goal in this specific situation? Create a new comment for every test run and delete the previous comment? That would make sure there's only ever the latest result visible, but it won't be buried in the beginning of the thread. Right now, the action just updates the existing comment, which is fine in most scenarios.

The action you've linked looks pretty neat — I might just rip out my commenting logic and defer to something like this entirely. That way, everybody is free to choose their own implementation of creating and updating the pr comment...

**Comment by daun** [comment]
I'll close this for now to keep things tidy. Feel free to comment with some more context to re-open.

**Comment by tarungunampalli1** [comment]
I also like the logic in the sticky-comment action. It allows the removal of a comment as well (in my case, I only want to use your comment if we failed tests, and so if one run fails and I use your comment, and then a following run passes, I would like to remove your comment to display my own)
