### ISSUE TITLE
[Feature] Support to post multiple comments without overwriting existing comments

### ISSUE THREAD

**Issue by ZuzanaMihalyiova** [daun/playwright-report-summary#216]
First of all, thank you for this incredibly helpful tool!

Currently, the action overwrites existing comments when it runs. While this behavior can be useful in some cases, I have a workflow where PRs run multiple Playwright tests from different sources. For example:
- API tests
- UI tests

In this situation, I need the ability to post multiple comments on the same PR, instead of having the latest one overwrite the previous comment. 

**Request**  
Could you please add a feature that allows the action to post multiple comments without overwriting the existing ones? 

Thanks a lot!

**Comment by daun** [comment]
This already exists :) When you pass in a different `report-tag` option to each test report, it will only overwrite the comments if they were created by that report. [See this comment for an example](https://github.com/daun/playwright-report-summary/issues/68#issuecomment-1854770114).

**Comment by azad-resolver** [comment]
What I'm looking for is an option for it to not overwrite existing comments at all, I don't think that's possible with the solution in your linked comment? @daun 

My usecase is not about running different tests (therefore adding multiple steps with a different `report-tag` is not an option), it could be the exact same tests. I'd just like to have each test run produce its own comment.
Should I create a new ticket for that?

**Comment by azad-resolver** [comment]
Oh cool, that approach of random report tags hadn't occured to me, thanks! I'll try that with the timestamp. :)
