### ISSUE TITLE
Possibility to customise the report

### ISSUE THREAD

**Issue by eleven4y** [daun/playwright-report-summary#67]
Problem:
We allure report and want to write link to allure report in comment with playwright summary

Solution:
Add possibility to customise message with report by some parameters, which allow add content before and after body of report

**Comment by daun** [comment]
What's "allure"?

**Comment by daun** [comment]
How would you imagine this to work ideally? I've been thinking about returning the summary as an output parameter, in that case you could create/update the comment yourself.

**Comment by eleven4y** [comment]
> What's "allure"?

we use [allure-playwright](https://www.npmjs.com/package/) package and want to generate and post one comment message to each our pull, which contain result of tests (exist in current version of action) and link to allure run of tests. 

> How would you imagine this to work ideally?

i thought about some parameter which make possibility to append some text to current summery, in addition section. Something like in [action-gh-release](https://github.com/softprops/) via `body` and `append_body` input arguments

**Comment by daun** [comment]
The action has an input parameter `report-url`. Passing in a URL here will render a link to that url marked as "Open report". Maybe that's already enough? Or do you need to append/prepend actual longer text?

```
- uses: daun/playwright-report-summary@v2
  with:
    report-url: 'https://url.to/allure/report'
```

**Comment by eleven4y** [comment]
checked and it's fully cover my case, thanks for quick response
i close issue

**Comment by daun** [comment]
Sweet 🧃
