### ISSUE TITLE
Get associated PR from `push` event

### ISSUE THREAD

**Issue by DrJume** [daun/playwright-report-summary#99]
Hi, thank you so much for this GitHub Action. It's looks awesome!

There is one thing I wish it could do: Get the associated PR from a `push` event.

Because, when pushing onto an existing PR, it doesn't create/update a test report PR comment.

**Comment by daun** [comment]
If I understand correctly, this should be supported. Probably a question of how and when you run the action. We're using it for PRs on [swup/swup](https://github.com/swup/swup) where it definitely updates the existing PR comment after pushing to it. You might look into the [workflow file](https://github.com/swup/swup/blob/master/.github/workflows/e2e-tests.yml) over there to see if the setup is different than yours.
